
# Loads default set of integrations. Do not remove.
# default_config:

# --- 1. ABSOLUTE BASIS-DIENSTE & THEMES ---
api:
websocket_api:
http:
system_health:
person:
zone:

# --- 2. LOGS & VERLAUF REDUZIEREN (Für Pi 2B) ---
logger:
  default: warning

recorder:
  purge_keep_days: 3
  commit_interval: 30

history:
logbook:

# Load frontend themes from the themes folder
frontend:
#  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
  - platform: rpi_gpio
    switches:
      - port: 22
        name: "Licht I"
        unique_id: "relais_1"
      - port: 23
        name: "Licht II"
        unique_id: "relais_2"

mqtt:
  sensor:
    - name: "Kompass"
      state_topic: "home/sensors/gy511"
      value_template: "{{ value_json.heading }}"
      unit_of_measurement: "°"
      icon: "mdi:compass"

    - name: "Neigung Längsachse"
      state_topic: "home/sensors/gy511"
      value_template: "{{ value_json.y_neigung }}"
      unit_of_measurement: "°"
      icon: "mdi:axis-x-arrow"

    - name: "Neigung Querachse"
      state_topic: "home/sensors/gy511"
      value_template: "{{ value_json.x_neigung }}"
      unit_of_measurement: "°"
      icon: "mdi:axis-y-arrow"

    - name: "Feuchtigkeitssensor"
      state_topic: "home/sensors/gy511"
      value_template: "{{ value_json.fs }}"
      unit_of_measurement: "V"
      icon: "mdi:water"

    - name: "Eingangsspannung I"
      state_topic: "home/sensors/gy511"
      value_template: "{{ value_json.vin1 }}"
      unit_of_measurement: "V"
      icon: "mdi:flash"

    - name: "Eingangsspannung II"
      state_topic: "home/sensors/gy511"
      value_template: "{{ value_json.vin2 }}"
      unit_of_measurement: "V"
      icon: "mdi:car-battery"

#notify:
#  - name: "email_alarm"
#    platform: smtp
#    server: "smtp.web.de"            # <-- Wichtig: Der WEB.DE Server
#    port: 587
#    encryption: starttls
#    timeout: 15
#    sender: "ingeburg.bauer@web.de"     # Deine WEB.DE Adresse
#    username: "ingeburg.bauer@web.de"   # Nochmal deine WEB.DE Adresse
#    password: "password"                # web.de Passwort (kein App-Passwort nötig)
#    recipient: "harald.n.bauer@web.de"  # Wo soll die Mail ankommen?
#    sender_name: "HomeAssistant"
#

notify:
  - name: "email_alarm"
    platform: smtp
    server: "mail.gmx.net"              # <-- Wichtig: Der GMX Server
    port: 587
    encryption: starttls
    timeout: 15
    sender: "home_a@gmx.de"             # GMX Adresse
    username: "home_a@gmx.de"           # Nochmal die GMX Adresse
    password: !secret gmx_password      # GMX Passwort (kein App-Passwort nötig)
    recipient: "harald.n.bauer@web.de"  # Wo soll die Mail ankommen?
    sender_name: "HomeAssistant"

rest_command:
  shutdown_pi_host:
    url: "http://localhost:8080/shutdown_host" # IP deines Pi einsetzen
    method: POST

